### PR TITLE
Smarto_learning_210311_version update

### PR DESCRIPTION
**Pull request by Jiangjiajun-Dominic**
[Developer] Jiajun Jiang
[Commit] 16:05 10/Mar
[Description] complete the " learning " part preliminarily,create the function to play,pause,resume and stop music by using QAudioInput.
Screenshot from 2021-03-10 23-30-10
Screenshot from 2021-03-10 23-29-47

### CODE REVIEW

**Comment by Zi-han-Huang** [comment]
Can the name of the pull request be Smarto_learning_210311_version update?

**Comment by Zi-han-Huang** [comment]
Screenshot from 2021-03-11 16-06-48
There is no build directory.

**Comment by Jiangjiajun-Dominic** [comment]
> Screenshot from 2021-03-11 16-06-48
> There is no build directory. I think you may need to add one:)

Of course,we need create an empty file folder named build first.

**Comment by Jiangjiajun-Dominic** [comment]
> > Screenshot from 2021-03-11 16-06-48
> > There is no build directory. I think you may need to add one:)
> 
> Of course,we need create an empty file folder named build first.
> 
> Ahhh, that's not user-friendly. Or you can change your Readme file by adding "mkdir build":)

That's great!

**Comment by Zi-han-Huang** [comment]
ok

**Pull request merged**
